# Generated by Django 3.1.4 on 2021-01-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=30)),
                ('Site', models.CharField(max_length=50)),
                ('Subscrprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prise', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('PhoneBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.phonebrand')),
            ],
        ),
    ]
